ALTER TABLE public.penelitian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anggota_penelitian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publikasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hki ENABLE ROW LEVEL SECURITY;
